name: CI

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: json2csv-rs
            asset_name: json2csv-linux-amd64
          - os: windows-latest
            artifact_name: json2csv-rs.exe
            asset_name: json2csv-windows-amd64
          - os: macos-latest
            artifact_name: json2csv-rs
            asset_name: json2csv-macos-amd64
    steps:
      - uses: actions/checkout@v2
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Build release executable
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
      - name: Publish binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
        if: ${{ startsWith(github.ref, 'refs/tags/') }}